# Generated by Django 4.1.4 on 2023-01-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Client'), (2, 'Admin'), (3, 'Script Writer'), (4, 'Video Editor'), (5, 'Staff Admin')], null=True),
        ),
    ]
