# Generated by Django 4.1.4 on 2023-01-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_name_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Client'), (2, 'Admin'), (3, 'Script Writer'), (4, 'Video Editor'), (5, 'Full Stack'), (6, 'Staff Admin')], null=True),
        ),
    ]
