# Generated by Django 4.1.4 on 2023-01-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostProductionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.DateTimeField(blank=True, null=True)),
                ('has_editing', models.BooleanField(default=True)),
                ('has_internal', models.BooleanField(default=True)),
                ('has_delivery', models.BooleanField(default=True)),
                ('complete_editing', models.BooleanField(default=False)),
                ('complete_internal', models.BooleanField(default=False)),
                ('complete_delivery', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PreProductionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_video', models.BooleanField(default=True)),
                ('has_location', models.BooleanField(default=True)),
                ('has_props', models.BooleanField(default=True)),
                ('has_file', models.BooleanField(default=True)),
                ('has_model', models.BooleanField(default=True)),
                ('complete_video', models.BooleanField(default=False)),
                ('complete_location', models.BooleanField(default=False)),
                ('complete_props', models.BooleanField(default=False)),
                ('complete_file', models.BooleanField(default=False)),
                ('complete_model', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_completion', models.DateTimeField(blank=True, null=True)),
                ('complete_video', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('commoncontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.commoncontent')),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.commoncontent', models.Model),
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('commoncontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.commoncontent')),
                ('duration', models.TimeField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('content.commoncontent', models.Model),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_contents', models.ManyToManyField(related_name='post_production_content', to='content.postproductioncontent')),
                ('pre_contents', models.ManyToManyField(related_name='pre_production_content', to='content.preproductioncontent')),
            ],
        ),
    ]
