# Generated by Django 4.1.4 on 2023-01-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_name', to='product.product'),
        ),
        migrations.AddField(
            model_name='section',
            name='production_contents',
            field=models.ManyToManyField(related_name='production_content', to='content.productioncontent'),
        ),
        migrations.AddField(
            model_name='preproductioncontent',
            name='location',
            field=models.ManyToManyField(related_name='location', to='content.commoncontent'),
        ),
        migrations.AddField(
            model_name='preproductioncontent',
            name='model',
            field=models.ManyToManyField(related_name='model', to='content.commoncontent'),
        ),
        migrations.AddField(
            model_name='preproductioncontent',
            name='props',
            field=models.ManyToManyField(related_name='props', to='content.commoncontent'),
        ),
        migrations.AddField(
            model_name='postproductioncontent',
            name='editing',
            field=models.ManyToManyField(related_name='editing', to='content.commoncontent'),
        ),
        migrations.AddField(
            model_name='postproductioncontent',
            name='internal',
            field=models.ManyToManyField(related_name='internal_feedback', to='content.commoncontent'),
        ),
        migrations.AddField(
            model_name='commoncontent',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='content.comments'),
        ),
        migrations.AddField(
            model_name='comments',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.comments'),
        ),
    ]
