# Generated by Django 4.1.4 on 2023-01-12 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Commenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='video_content',
            field=models.ManyToManyField(related_name='Video_Content', to='content.videocontent'),
        ),
        migrations.AddField(
            model_name='preproductioncontent',
            name='file_contents',
            field=models.ManyToManyField(related_name='file_content', to='content.filecontent'),
        ),
        migrations.AddField(
            model_name='preproductioncontent',
            name='video_contents',
            field=models.ManyToManyField(related_name='video_content', to='content.videocontent'),
        ),
    ]
