# Generated by Django 4.1.4 on 2023-01-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preproductioncontent',
            name='video_contents',
        ),
    ]
