# Generated by Django 4.1.4 on 2023-01-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_preproductioncontent_video_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncontent',
            name='comment',
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='files',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commoncontent',
            name='comment',
            field=models.ManyToManyField(related_name='Content_Comment', to='content.comments'),
        ),
    ]
