# Generated by Django 4.1.4 on 2023-01-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_commoncontent_comment_alter_filecontent_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontent',
            name='has_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='has_approved',
            field=models.BooleanField(default=False),
        ),
    ]
