# Generated by Django 4.1.4 on 2023-01-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_filecontent_has_approved_videocontent_has_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncontent',
            name='comment_off',
            field=models.BooleanField(default=False),
        ),
    ]
