# Generated by Django 4.1.4 on 2023-01-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_commoncontent_comment_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preproductioncontent',
            name='complete_video',
        ),
        migrations.RemoveField(
            model_name='preproductioncontent',
            name='has_video',
        ),
    ]
