# Generated by Django 4.1.4 on 2023-01-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_preproductioncontent_complete_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncontent',
            name='comment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
