# Generated by Django 4.1.4 on 2023-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_commoncontent_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
