# Generated by Django 4.1.4 on 2023-02-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_videocontent_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncontent',
            name='has_video',
            field=models.BooleanField(default=True),
        ),
    ]
