# Generated by Django 4.1.4 on 2023-01-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_completed',
            field=models.BooleanField(default=False),
        ),
    ]
